name: Shared Schemas Version

on:
  workflow_dispatch: # manual manual trigger via GitHub UI

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Version Number and Push With Tag
        run: |
          GIT_TAG=$(date +%Y.%m%d.%H%M)
          echo "GIT_TAG is: $GIT_TAG"
          echo "CALVER_VERSION=$GIT_TAG" >> version.env
          git config --global user.email kenneth.man@digital.mod.uk
          git config --global user.name kenneth-man
          git tag -a "$GIT_TAG" -m "$GIT_TAG"
          git push origin "$GIT_TAG"

      - name: Upload Version Environment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-env
          path: version.env