name: Signal Store Deploy Staging

on:
  push:
    branches: ["staging"]

jobs:
  build-and-test:
    uses: ./.github/workflows/signal-store-build-and-test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Deploy Staging Workflow Running..."