name: Signal Store Deploy Dev

env:
  TF_ENV: development
  TESTURL: ${{secrets.TESTING_SECRET}}/projects/terraform/state/development

on:
  push:
    branches: ["dev"]

jobs:
  build-and-test:
    uses: ./.github/workflows/signal-store-build-and-test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Deploy Dev Workflow Running..."

      - name: Test Echo Env
        run: echo "Test...$TESTURL"