name: Reusable Signal Store Build And Test

on:
  push:
    branches-ignore: ["dev", "staging", "prod"]
  workflow_call:

jobs:
  authenticate-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: docker login --username kennethman97 --password ${{secrets.CLASSIC_PAT}} ghcr.io

  build-and-test:
    runs-on: ubuntu-latest
    container: ghcr.io/kennethman97/poetry-ci-test-ghcr:latest # to remove; testing using ghcr image
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Reusable Workflow Running..."
      
      - name: Test GHCR Image
        run: |
          poetry --version
          aws-cli --version
          git --version
    needs: [authenticate-ghcr]