name: Reusable Signal Store Build And Test

on:
  push:
    branches-ignore: ["dev", "staging", "prod"]
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ghcr.io/kennethman97/poetry-ci-test-ghcr:latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Reusable Workflow Running..."
      
      - name: Test Container
        run: |
          poetry --version
          aws-cli --version
          git --version