name: Signal Store Deploy Dev

on:
  pull_request:
    branches: ["dev"]

jobs:
  build-and-test:
    uses: ./.github/workflows/signal-store-build-and-test.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Deploy Dev Workflow Running..."