name: Reusable Signal Store Build And Test

on:
  push:
    branches: "*"
    branches-ignore: ["dev", "staging", "prod"]
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Echo
        run: echo "Resuabled Workflow Running..."